# The Kafka broker location (defaults to localhost:9092)
kafka:
  bootstrap:
    servers: localhost:9092

mp:
  messaging:
    # Configuring the incoming channel (reading from Kafka)
    incoming:
      movies-in:
        connector: smallrye-kafka
        topic: movies
        key:
          deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
    # Configuring the outgoing channel (writing to Kafka)
    outgoing:
      movies-out:
        connector: smallrye-kafka
        topic: movies
        key:
          serializer: org.apache.kafka.common.serialization.IntegerSerializer
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
